apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../upstream

patches:
- path: patch-deployment-argocd-server-insecure.yaml
  target:
    kind: Deployment
    name: argocd-server
